### LLM settings ###

completion_models:
  default_completion_model:
    model_provider: openai
    auth_method: api_key
    api_base: ${CHAT_API_BASE}
    api_key: sk-xxx
    model: default 
    retry:
      type: exponential_backoff

embedding_models:
  default_embedding_model:
    model_provider: openai
    auth_method: api_key
    api_base: ${EMBED_API_BASE}
    api_key: sk-xxx
    model: default
    retry:
      type: exponential_backoff

### Document processing settings ###

input:
  type: json

chunking:
  type: tokens
  size: 1200
  overlap: 100
  encoding_model: o200k_base

### Storage settings ###

input_storage:
  type: file # [file, blob, cosmosdb]
  base_dir: "input"

output_storage:
  type: file # [file, blob, cosmosdb]
  base_dir: "output"

reporting:
  type: file # [file, blob]
  base_dir: "logs"

cache:
  type: json # [json, memory, none]
  storage:
    type: file # [file, blob, cosmosdb]
    base_dir: "cache"
    
vector_store:
  type: lancedb
  db_uri: output/lancedb

### Workflow settings ###

embed_text:
  embedding_model_id: default_embedding_model

extract_graph:
  completion_model_id: default_completion_model
  prompt: "prompts/extract_graph.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  completion_model_id: default_completion_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: false
  completion_model_id: default_completion_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  completion_model_id: default_completion_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

snapshots:
  graphml: false
  embeddings: false

### Query settings ###

local_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  completion_model_id: default_completion_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_search_reduce_prompt.txt"

basic_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"
